version: "3.8"

services:
 
  backend:
    build: ./backend
    container_name: campus-life-backend
    ports:
      - "5000:5000"   
    environment:
      NODE_ENV: production
      
      DATABASE_URL: postgres://campus_user:campus_pass@db:5432/campus_life
    volumes:
      - backend-data:/app/data
    depends_on:
      - db

  
  frontend:
    build: ./frontend
    container_name: campus-life-frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: campus-life-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: campus_user
      POSTGRES_PASSWORD: campus_pass
      POSTGRES_DB: campus_life
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  backend-data:
  db-data:
